### ISSUE TITLE
Why move the last tab to the front?

### ISSUE THREAD

**Issue by than** [plainlanguage/statamic-section-tabs#2]
Just curious about this line... What was the reason?

```		
// Move the last one to the front. Because.
tabs.find('a').last().prependTo(tabs);
```

**Comment by chadclark** [comment]
With the release of Statamic 1.10.1, there is now a `field_order` [fieldset setting](http://statamic.com/learn/control-panel/fields-and-fieldsets#field_order) to control field order, including `includes`.

[Version 1.2](https://github.com/plainlanguage/statamic-section-tabs/releases/tag/v1.2) no longer changes the order of the tabs.

**Comment by than** [comment]
👍
